'use client';
import {useMemo,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import atlas from '@/data/neuro_atlas.json';
import headband from '@/data/headband.json';

function exportJson(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Source({id}:{id:string}){const s=atlas.sources.find(x=>x.id===id);return s?<a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>:<span>Source unresolved</span>}
function Choice({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(s:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} items={values.map(x=>({value:x,label:x}))} onValueChange={x=>{if(x!==null)onChange(String(x));}}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>}

export function NeuroAtlas(){
 const [query,setQuery]=useState(''),[population,setPopulation]=useState('All populations'),[priority,setPriority]=useState('All priorities');
 const filtered=useMemo(()=>atlas.datasets.filter(x=>(population==='All populations'||x.species===population)&&(priority==='All priorities'||x.priority===priority)&&[x.name,x.modality,x.ida_test,x.usual_use,x.limit].join(' ').toLowerCase().includes(query.toLowerCase())),[query,population,priority]);
 return <div className="neuroatlas"><section className="panel"><div className="toolbar"><div><p className="eyebrow">NEUROSCIENCE → IDA · REVIEWED 8 SEPTEMBER 2026</p><h2>Find data that can answer the next question.</h2></div><Button variant="outline" onClick={()=>exportJson('ida-neuroscience-atlas.json',atlas)}>Export full map</Button></div><div className="statrow"><div><b>{atlas.datasets.length}</b><span>data resources</span></div><div><b>{atlas.modalities.length}</b><span>measurement families</span></div><div><b>{atlas.failures.length}</b><span>failure modes</span></div><div><b>{atlas.sources.length}</b><span>source records</span></div></div><p>{atlas.scope}</p><div className="atlasfilters"><label className="field"><span>Search measurements, outcomes or datasets</span><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="EEG, repeated sessions, treatment, sleep…"/></label><Choice label="Population" value={population} values={['All populations','Human','Animal','Mixed']} onChange={setPopulation}/><Choice label="IDA research priority" value={priority} values={['All priorities','High','Medium','Low']} onChange={setPriority}/></div><p aria-live="polite">{filtered.length} resources match. Priority describes usefulness for the next research step, not probability of a cure.</p><div className="paperlist">{filtered.map(d=><article key={d.id}><span className="pill">{d.id} · {d.species} · {d.priority} priority</span><h3>{d.name}</h3><p><b>Measures:</b> {d.modality}<br/><b>Design:</b> {d.design}</p><p><b>Usual use:</b> {d.usual_use}</p><p><b>IDA test:</b> {d.ida_test}</p><p className="smallnote"><b>Limit:</b> {d.limit}<br/><b>Access:</b> {d.access}<br/><b>Audit:</b> {d.audit}</p><Source id={d.source}/></article>)}</div>{!filtered.length&&<div className="callout">No resource matches these filters. Clear the search or select a broader population.</div>}</section>
 <section className="panel spaced"><h2>What each measurement actually observes</h2><Table><TableHeader><TableRow><TableHead>Family</TableHead><TableHead>Observation and methods</TableHead><TableHead>What limits the inference</TableHead><TableHead>R1 decision</TableHead></TableRow></TableHeader><TableBody>{atlas.modalities.map(m=><TableRow key={m.name}><TableCell><b>{m.name}</b></TableCell><TableCell>{m.observes}<br/><span className="smallnote">{m.methods}</span></TableCell><TableCell>{m.limit}</TableCell><TableCell>{m.decision}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="panel spaced"><h2>Failure modes the project must withstand</h2><p>These are documented problems, inference limits and declared hypotheses. They are not accusations that the whole field uses the same methods incorrectly.</p>{atlas.failures.map(f=><details key={f.id}><summary>{f.id} · {f.title}</summary><span className="pill">{f.status}</span><p className="spaced">{f.problem}</p><p><b>Repair:</b> {f.repair}<br/><b>Acceptance:</b> {f.acceptance}</p><Source id={f.source}/></details>)}</section>
 <section className="panel spaced"><h2>Where an intervention discovery could emerge</h2><div className="paperlist">{atlas.routes.map(r=><article key={r.id}><span className="pill">{r.priority}</span><h3>{r.title}</h3><p>{r.rationale}</p><p><b>Next test:</b> {r.next_test}</p><p className="smallnote"><b>Boundary / stop:</b> {r.stop}</p><Source id={r.source}/></article>)}</div></section>
 <section className="panel spaced"><h2>Coverage and unresolved work</h2><p>{atlas.review_method}</p><p>{atlas.completion}</p><ul className="steps">{atlas.open_coverage.map(x=><li key={x}>{x}</li>)}</ul><details><summary>Complete source register</summary>{atlas.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><br/><span className="smallnote">{s.kind}</span></p>)}</details></section></div>
}

export function Headband(){
 const [status,setStatus]=useState('All requirements');const reqs=headband.requirements.filter(r=>status==='All requirements'||(status==='Software / geometry evidence'?r.status.includes('passed'):(!r.status.includes('passed')||/pending|unvalidated/.test(r.status))));
 return <div><section className="panel"><div className="toolbar"><div><p className="eyebrow">IDA R1 · ENGINEERING BASELINE</p><h2>A modular instrument for testing measurement value.</h2></div><a className="downloadlink" href="/engineering/ida-r1-package.zip" download>Download engineering package ↓</a></div><p>{headband.selected}.</p><div className="callout"><b>{headband.status}.</b><p className="spaced">The package includes the architecture, requirements, connection worksheet, bill of materials, prototype CAD, decoder, synthetic tests and physical verification plan. No custom PCB, fabricated unit or validated mental-health treatment is claimed.</p></div><img className="engineeringdrawing" src="/engineering/carrier.svg" alt="Dimensioned R1 prototype carrier and acquisition system drawing; fit dimensions are assumptions" width="1100" height="570"/><div className="actions"><a href="/engineering/carrier.svg" download>Download drawing</a><a href="/engineering/carrier.stl" download>Prototype STL</a><a href="/engineering/carrier.scad" download>Parametric CAD</a><Button variant="outline" onClick={()=>exportJson('ida-headband-requirements.json',headband)}>Export engineering record</Button></div></section>
 <section className="panel spaced"><h2>Selected design</h2><div className="gridtwo"><article><h3>Acquisition and artifact controls</h3><p>Six EEG channels: Fp1, Fp2, F7, F8, O1, O2. Two differential EOG channels. Separate reference and bias. Twelve contacts in the proposed harness.</p><p>Use the OEM module, insulating case, battery, radio and supported firmware. Preserve raw counts and verified configuration. Place the pod off-head if fit, weight or movement makes the rear carrier unsuitable.</p><p className="smallnote">EOG does not measure pupil diameter. Reference, bias and lead-off behaviour need an actual hardware audit. No brain-stimulation circuit is included.</p></article><article><h3>Proposed acceptance targets</h3><p>250 samples/s · 8 channels. Noise ≤1 µV RMS in the declared band. Gain error ±5% at 10 Hz. Event timing p95 ≤20 ms for seconds-scale experiments.</p><p>These are targets to test, not measured performance. Fast phase-control applications need a separate latency design. Fit dimensions and contact geometry must be measured before fabrication.</p><p className="smallnote">The 88 × 88 × 8 mm carrier mesh passes analytic geometry checks. It has not been sliced, printed, stress-tested or fitted.</p></article></div></section>
 <section className="panel spaced"><h2>Executed synthetic bench tests</h2><p>13 decoder and quality tests passed. Five invented signal/fault scenarios were run; they contain no human EEG and do not test physical hardware.</p><Table><TableHeader><TableRow><TableHead>Fixture</TableHead><TableHead>Frames</TableHead><TableHead>Continuity issues</TableHead><TableHead>Usable quality windows</TableHead></TableRow></TableHeader><TableBody>{Object.entries(headband.bench.cases).map(([name,c])=><TableRow key={name}><TableCell>{name.replaceAll('_',' ')}</TableCell><TableCell>{c.frames}</TableCell><TableCell>{c.continuity_issues}</TableCell><TableCell>{c.usable_windows} / {c.windows}</TableCell></TableRow>)}</TableBody></Table><p className="smallnote">Quality thresholds are candidates, not artifact-free certification. Packet counters cannot reveal all resets or loss, and the protocol supplies no CRC.</p><Button variant="outline" onClick={()=>exportJson('ida-synthetic-bench-results.json',headband.bench)}>Export bench results</Button></section>
 <section className="panel spaced"><div className="toolbar"><h2>Requirements and evidence</h2><Choice label="Evidence filter" value={status} values={['All requirements','Software / geometry evidence','Remaining verification']} onChange={setStatus}/></div><p>{reqs.length} requirements shown.</p>{reqs.map(r=><details key={r.id}><summary>{r.id} · {r.title} — {r.status}</summary><p>{r.requirement}</p><p><b>Verification:</b> {r.verification}<br/><b>Linked atlas failure:</b> {r.failure}</p></details>)}</section>
 <section className="panel spaced"><h2>Bill of materials</h2><p>Engineering selections; no components ordered, prices quoted or substitutions qualified.</p><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Qty</TableHead><TableHead>Requirement</TableHead></TableRow></TableHeader><TableBody>{headband.bom.map(b=><TableRow key={b.id}><TableCell><b>{b.id} · {b.item}</b></TableCell><TableCell>{b.quantity}</TableCell><TableCell>{b.requirement}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="panel spaced"><h2>The gate to a finished physical product</h2><p>First verify acquisition, timing, safety and fit on the actual assembly. Then test usable repeated measurements, incremental information beyond simpler channels, and finally the benefit of state-guided delivery on independent later outcomes. Those gates determine the production sensor set and controller.</p><p>The project is prepared for GitHub handoff. Repository ownership and visibility still need to be selected; the current site remains private.</p></section></div>
}
